### ISSUE TITLE
app freezing and command not work

### ISSUE THREAD

**Issue by HenryTung2022** [itsMeDavidV/Watchla-Support#224]
after using the new api. the app keep freezing and command always fail. basically not able to use the app to perform

**Comment by kamsimon** [comment]
Same here!

**Comment by Tophertopher** [comment]
Same here!! App updates on phone but not on watch. It’s useless now.

**Comment by yoshiat** [comment]
+1 even after 3.5.2, this freezing is still happening. It seems to freeze when the app wakes the vehicle. When I turned on “do not wake”, this doesn’t seem to happen. Not a good workaround because, it does freeze when the watch connects via Bluetooth after all…

**Comment by itsMeDavidV** [comment]
@yoshiat have you ensured that your watch app is also updated to version 3.5.2 (325) by opening Preferences in the watch app and scrolling down to the version indicator?

If so, can you please send over your Watchla support code **that is found on your watch app** to https://watchla.app/contact ? Please be sure to reference this issue when you do.

**Comment by itsMeDavidV** [comment]
For everyone facing this issue, we are piloting a new polling system that should fix this issue in v3.5.2 which was just released hours ago. To fix this issue you'll want to ensure that your Watchla watch app updates to that version or later. Sometimes watch apps tend to not update immediately after their counterpart iOS apps. If this happens to you, you can update your watch app directly on the App Store app on your Apple Watch.

If you continue to face freezing after you have verified that your watch app is on v3.5.2, please send in your Watchla support code (found on your watch app in the support screen) to https://watchla.app with a short description of what happened right before the freeze and a reference to this issue. Thanks!

**Comment by itsMeDavidV** [comment]
> command always fail

@HenryTung2022 have you setup your virtual key in the Tesla app?

**Comment by claire078** [comment]
> > command always fail
> 
> @HenryTung2022 have you setup your virtual key in the Tesla app?

Hi David,
please explain to me. what is the different between “watch key” and virtual key? What they for?
Both need to have it?
Phone app also has a virtual key. All should have to installed?

I also have freezing after update to 3.52.
My code is [redacted]. 

Relevant vehicle status companion shows blank. 
Thx for your support!

**Comment by Tophertopher** [comment]
DavidYes I did set up virtual key in the app. Didn’t help. On Jan 18, 2024, at 12:53 PM, David Villegas ***@***.***> wrote:﻿

command always fail

@HenryTung2022 have you setup your virtual key in the Tesla app?

**Comment by zunzster** [comment]
I've just updated to 3.5.2 and the app is still freezing - current frozen on the charge stats page which comes up when I use the complication.

**Comment by Dinoraptor101** [comment]
> For everyone facing this issue, we are piloting a new polling system that should fix this issue in v3.5.2 which was just released hours ago. To fix this issue you'll want to ensure that your Watchla watch app updates to that version or later. Sometimes watch apps tend to not update immediately after their counterpart iOS apps. If this happens to you, you can update your watch app directly on the App Store app on your Apple Watch.
> 
> If you continue to face freezing after you have verified that your watch app is on v3.5.2, please send in your Watchla support code (found on your watch app in the support screen) to https://watchla.app with a short description of what happened right before the freeze and a reference to this issue. Thanks!


can confirm, that this resolved the issue, (had to install the Watchla app from the App Store on the watch itself to get the new version.

what could make this better is friendly “loading” indicators to avoid the perception of freeze.

**Comment by Dinoraptor101** [comment]
> I've just updated to 3.5.2 and the app is still freezing - current frozen on the charge stats page which comes up when I use the complication. When it unfreezes, I'll add my watchla support code. It took quite a while to unfreeze. The code is LkNvCP9gGj.

------
Is both phone and watch apps using the new version?

**Comment by zunzster** [comment]
I just noticed the Phone app was pending an update. I've updated that too which didn't help but then forcing a Watch app refresh from the Phone app seemed to get it responding. I'll see how it goes from here.

**Comment by zunzster** [comment]
I notice in the version info area the last vehicle data update shows --:--- -- (i.e. null). Does that only update for bluetooth?

**Comment by itsMeDavidV** [comment]
Hi everyone, to clarify most of the freezing was occurring on Home View, so we piloted a new polling system in v3.5.2 that would fix the freeze issue on just the Home View before applying to the rest of the watch app. So far that pilot looks to be preventing freezes so we have applied it to other parts of the app (like Charge Stats) and an update with this change will be in beta tonight, followed by an App Store update most likely in the morning (PST)

If you'd like to test the beta update that addresses this issue, please send over your Watchla Support code along with a mention to  this support issue to https://watchla.app/contact.

**Note:** please do not post your support code here.

**Comment by itsMeDavidV** [comment]
> I notice in the version info area the last vehicle data update shows --:--- -- (i.e. null). Does that only update for bluetooth?

No, this is a minor UI bug that will be addressed soon.

**Comment by HenryTung2022** [comment]
> > command always fail
> 
> 
> 
> @HenryTung2022 have you setup your virtual key in the Tesla app?


Yes. I did setup the virtual key. Also I try to reinstall the app with 3.5.2. However, app freezing still happen. Also the command from watch over 80% of time doesn't work.

Thank you

**Comment by yoshiat** [comment]
> @yoshiat have you ensured that your watch app is also updated to version 3.5.2 (325) by opening Preferences in the watch app and scrolling down to the version indicator?
> 
> If so, can you please send over your Watchla support code **that is found on your watch app** to https://watchla.app/contact ? Please be sure to reference this issue when you do.

Ack, will file a report.  Yes, I’m on 3.5.2 (325) and the app froze this afternoon.

**Comment by yoshiat** [comment]
@itsMeDavidV Sent the support code last night and it froze constantly this morning. AFAICT the Bluetooth connection and waking the vehicle seems to trigger the bug. When I restart the app, it can work around the issue.

Hope this helps.

**Comment by itsMeDavidV** [comment]
Hi everyone, V3.5.3 was released yesterday and it should fix this issue for the most part. There is still one more small part to this to be fixed in 3.5.4, but for the most part, most of the freezing issues should be resolved.

Could everyone please update their watch apps and test this new update? Thanks!

**Comment by yoshiat** [comment]
Hi @itsMeDavidV 

Just sent the support code but 3.5.3 stills freezes when it connects. It crashes after a while and the app starts fresh, things seem to work.

So it must be the state transitions somewhere in between that’s different from the fresh start of the app IMO.

**Comment by itsMeDavidV** [comment]
@yoshiat about how frequently would you say the freezes occur?

**Comment by yoshiat** [comment]
> @yoshiat about how frequently would you say the freezes occur?

Interestingly it’s a bit sporadic… Just off the top of my head, 3 to 4 times out of 5 attempts, I feel the app freezes. It’s quite often but it doesn’t freeze 100% either.

**Comment by zunzster** [comment]
I'm on the very latest build (3.5.3) and it still mostly freezes for me, especially when near the vehicle - maybe when Bluetooth is available.

I'll hit the charge status complication - which no longer seems to update to what the charge stats are. It will show the charge stats with actual accurate % and it will often freeze there. If it doesn't and I can exit out to the main watchla screen (to say open frunk), it will freeze there instead. Whenever it does freeze it can be quite a few minutes before it recovers by which time the watch app will have turned off the screen and I have to keep tapping to see if it's become responsive. Sometimes it will crash and give either of the two spinning watchla startup screens whereas other times it just eventually unfreezes itself. 

In the old app, this used to work perfectly over bluetooth. Unlocking the charge point and opening the frunk/trunk are the two things I use the watchla app for mostly and it's unusable for those now.

I notice my watch is also draining battery way faster with the new watchla app installed too. I'm not sure if that's due to the freezing or if the new app just uses a lot more CPU and hence battery than before.

As an aside, the new complications are also unusable when using a Modular watch face with multicolour background since they become mostly white circles and I can barely make out the images. So I have to use a black background. I notice the complications grey out when I've taken the watch off until I sign in again which the old Complications didn't do - so if my watch was on the bedside I could still see the charge status.

**Comment by itsMeDavidV** [comment]
Hi @zunzster thanks for reporting. We do believe that Bluetooth communications are a factor at play here for freezing. Have you taken notice of your Apple Watch and your vehicle's internet connection during the times that freezing occurs? And if so do you notice slower than ideal internet connection?

**Comment by yoshiat** [comment]
FYI I’m testing 3.5.4 beta and it seems better so far and files a feedback there. (wasn’t sure if I could disclose the details here in public.)

**Comment by itsMeDavidV** [comment]
@yoshiat That's good to hear! Generally unless you see a new feature that's not yet announced you should be fine to talk about things you came across in Watchla beta :) 

Additionally to provide an update on this matter, 3.5.4 removes a lot of legacy code that could potentially contribute to this issue. We've also focused in on an obscure bug that has affected a lot of people and could be a major root cause of this issue. We're addressing it now and we'll put out an update soon to see how it tests.

**Comment by yoshiat** [comment]
@itsMeDavidV Thanks, good to know. I’ve done a few more testing and the behaviors are interesting:
1. The chances of freezing is still there but getting close to 50/50. Either on WiFi or Bluetooth, this happens upon connecting to the vehicle. Not sure about the wake status.
2. The Bluetooth connection can work while the app may be frozen (!) but not all the time.
3. Reproducing this issue reliably is a bit hard.

**Comment by yoshiat** [comment]
Overall 3.5.4 (336) seems robust and responsive. The experience is smooth and better than the rewrite.

**Comment by itsMeDavidV** [comment]
Alright everyone, lets try this again. Can you all please download v3.5.4 to your Apple Watch and report back here? Remember it's important to verify that your watch app receives the update before testing as Apple Watches are prone to lag behind in automatic updates. You can verify that your Watchla watch app is on v3.5.4 at the bottom of the preferences screen in the watch app itself.

**Comment by Tophertopher** [comment]
The watchla app on the phone is updated to 3.5.4 but I can’t get the app on the watch to update. It’s on 3.5.3. Nothing I do will get the watch to update to the same version as the app version on the phone. On Jan 25, 2024, at 7:26 PM, David Villegas ***@***.***> wrote:﻿
Alright everyone, lets try this again. Can you all please download v3.5.4 to your Apple Watch and report back here? Remember it's important to verify that your watch app receives the update before testing as Apple Watches are prone to lag behind in automatic updates. You can verify that your Watchla watch app is on v3.5.4 at the bottom of the preferences screen in the watch app itself.

**Comment by itsMeDavidV** [comment]
@Tophertopher unfortunately this is the update lag I was referring to in watchOS. Have you tried directly updating the watch app in the App Store app on your Apple Watch?

**Comment by Tophertopher** [comment]
Aha! I honestly had no idea the watch had its own App Store app. I was using the one on the phone. I just updated it on the watch. Thanks. On Jan 25, 2024, at 9:22 PM, David Villegas ***@***.***> wrote:﻿
@Tophertopher unfortunately this is the update lag I was referring to in watchOS. Have you tried directly updating the watch app in the App Store app on your Apple Watch?

**Comment by HenryTung2022** [comment]
tested on 3.5.5, a bit better than  now, the commands sometimes work. but the app launch time take so long or it stay at loading page forever
