### ISSUE TITLE
Cannot sign in with Tesla account.  I have verified my Tesla login is correct but each time this error came up.

### ISSUE THREAD

**Issue by ericwanch** [itsMeDavidV/Watchla-Support#350]
![image](https://github.com/itsMeDavidV/Watchla-Support/assets/156725057/3035df98-760f-46ad-ae24-e6f9f3dbdd93)

**Comment by itsMeDavidV** [comment]
Hi @ericwanch thanks for reporting. Can you send over your Watchla support code via https://watchla.app/contact so that we can investigate? Please be sure to reference this issue.

**Comment by itsMeDavidV** [comment]
Hi @ericwanch sorry for the late reply, after reviewing error logs associated with your support code, it seems as though your device's secure keychain is rejecting Watchla's request to store your authentication details.

Going forward, I'd recommend deleting the Watchla app, restarting your device and then re-installing Watchla. After you do that I would attempt again.

**Comment by ericwanch** [comment]
I restarted my phone and reinstalled the app but same issue persists.

**Comment by itsMeDavidV** [comment]
Hi @ericwanch sorry to hear that. This issue seems to be prevalent in a small subset of people. We are currently investigating to see if the root of the issue is at the device level or the app level. If it's at the app level we will address it as soon as we can. 

Currently in beta, we have implemented and are testing a major authentication management overhaul that is testing very well. The overhaul also implements critical changes to how Watchla interacts with and uses your device's secure Keychain. I have had a TestFlight invite to Watchla's beta emailed over to you if you would like to see if any of these changes solve or alleviate your issue please feel free to accept the invite and join.

Regardless we will continue to investigate this issue and I will get back to you if any new info comes up.

**Comment by ericwanch** [comment]
Hi, I have installed the beta version via TestFlight to test. Same issue. Still can't authenticate. Prior to installing the test version, I uninstalled the original version and restarted the phone.

**Comment by CassandraMarie** [comment]
Hi @ericwanch, I apologize for the delayed response, are you still experiencing authentication issues?

**Comment by ericwanch** [comment]
Hi,
All good now. App is up and running. One thing that I noticed is that complication is not updated  eventhough I have all background wake etc. I used "battery state" and "relevant vehicle status". They are not showing current state of the car.

Kind Regards.

Eric Wan 

    On Thursday, September 26, 2024 at 07:59:13 AM GMT+10, Cassandra Marie ***@***.***> wrote:  
 
 


Hi @ericwanch, I apologize for the delayed response, are you still experiencing authentication issues?

**Comment by CassandraMarie** [comment]
Hi @ericwanch, we are currently working on refinements to improve the reliability of complications and background app refreshes. In the meantime, we recommend staying up to date with the latest version of Watchla.

**Comment by ericwanch** [comment]
Thank you.

Kind Regards.

Eric Wan 

    On Thursday, September 26, 2024 at 08:13:34 AM GMT+10, Cassandra Marie ***@***.***> wrote:  
 
 


Hi @ericwanch, we are currently working on refinements to improve the reliability of complications and background app refreshes. In the meantime, we recommend staying up to date with the latest version of Watchla.
